-- ============================================================================
-- Asesores con código y permisos por propiedad
-- Rama: pwa-movil · ver design_handoff_app_movil/paso6_asesores/ESPECIFICACION.md
-- ============================================================================
--
-- ANTES DE EJECUTAR, LEE ESTO:
--
-- 1. Corre esto contra una rama/branch de desarrollo de Supabase primero si
--    puedes, no directo contra producción. `main` de este repo sirve a
--    clientes reales, y aunque esta migración no toca datos existentes,
--    agrega columnas, tablas y policies nuevas que sí quieres probar.
--
-- 2. Verifica el TIPO real de las llaves primarias de `roles`, `proyectos_venta`
--    y `propiedades_venta` (uuid vs bigint/int8) en Supabase Studio → Table
--    editor, y ajusta las columnas marcadas [VERIFICAR TIPO] más abajo si no
--    coinciden. Esta migración asume bigint (el default actual de Supabase
--    para tablas nuevas) porque no tengo acceso de lectura al esquema en vivo.
--
-- 3. DESVIACIÓN DELIBERADA de ESPECIFICACION.md: la especificación dice
--    "reutiliza roles_propiedades / roles_proyectos" para el alcance del
--    asesor. Pero esas dos tablas YA se usan (ver src/App.tsx, SelectorAlcance)
--    para limitar al EQUIPO INTERNO sobre `propiedades` / `proyectos` — las
--    tablas de CARTERA (financiamiento, cuotas, pagos de clientes reales).
--    El asesor externo necesita alcance sobre `propiedades_venta` /
--    `proyectos_venta` — el CATÁLOGO DE VENTA (fotos, precio, para prospectar).
--    Son conjuntos de tablas distintos con ids independientes. Reutilizar
--    roles_propiedades tal cual mezclaría el alcance de cartera con el de
--    catálogo, y un asesor externo terminaría (en el mejor caso) sin poder
--    tener alcance real, o (en el peor) con una relación mal wireada.
--    Por eso aquí se crean roles_propiedades_venta / roles_proyectos_venta,
--    espejo exacto de las tablas existentes pero apuntando al catálogo.
--    El componente SelectorAlcance de la UI ya es genérico (recibe proyectos/
--    propiedades por props), así que se reutiliza tal cual, solo que alimentado
--    con datos del catálogo de venta en vez de la cartera.
--
-- 4. precio y precio_minimo NO se agregan a `propiedades_venta`. Esa tabla hoy
--    tiene una policy pública abierta (la usa el sitio web de ventas). Si el
--    precio mínimo de negociación viviera ahí, quedaría expuesto al público
--    con la misma policy — exactamente el tipo de fuga que CLAUDE.md pide
--    evitar. Por eso se crea `propiedades_venta_condiciones`, una tabla
--    aparte sin ninguna policy pública, solo legible por equipo/asesores
--    con permiso.
--
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1. Código de acceso y estado para todo el equipo (incluye asesores).
--    Los clientes ya usan un código de 6 dígitos (sin estas columnas, es un
--    mecanismo aparte). Este código es para equipo y asesores: 8 dígitos.
-- ----------------------------------------------------------------------------

alter table usuarios
  add column if not exists codigo text unique,
  add column if not exists activo boolean not null default true,
  add column if not exists tipo text not null default 'staff';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'usuarios_tipo_check'
  ) then
    alter table usuarios
      add constraint usuarios_tipo_check
      check (tipo in ('staff', 'asesor_interno', 'asesor_externo'));
  end if;
end $$;

comment on column usuarios.codigo is 'Código numérico de 8 dígitos para entrar (equipo y asesores). Se genera en el servidor, nunca en el navegador.';
comment on column usuarios.activo is 'Si es false, se rechaza el acceso aunque el código sea correcto. Se desactiva a mano, sin fecha de vencimiento.';
comment on column usuarios.tipo is 'staff (equipo interno, hoy con correo/contraseña) | asesor_interno | asesor_externo. Ver CLAUDE.md: no confundir con la tabla asesores (catálogo público, foto/teléfono).';

create index if not exists usuarios_codigo_idx on usuarios (codigo) where activo;

-- ----------------------------------------------------------------------------
-- 2. Condiciones privadas de venta (precio de lista y precio mínimo de
--    negociación) — tabla aparte de propiedades_venta a propósito, ver nota 4.
-- ----------------------------------------------------------------------------

create table if not exists propiedades_venta_condiciones (
  id bigint generated by default as identity primary key, -- [VERIFICAR TIPO]
  propiedad_venta_id bigint not null unique references propiedades_venta(id) on delete cascade, -- [VERIFICAR TIPO]
  precio numeric,
  precio_minimo numeric,
  financiamiento_tasa_anual numeric, -- tasa sugerida para precargar el cotizador del asesor
  actualizado_en timestamptz not null default now()
);

comment on table propiedades_venta_condiciones is 'Precio de lista y precio mínimo de negociación por propiedad del catálogo de venta. Deliberadamente separada de propiedades_venta (que tiene policy pública) para que el precio mínimo nunca sea legible por el sitio web público. Solo equipo/asesores con permiso.';

alter table propiedades_venta_condiciones enable row level security;

-- ----------------------------------------------------------------------------
-- 3. Alcance del catálogo de venta por rol (espejo de roles_propiedades /
--    roles_proyectos, pero apuntando a proyectos_venta / propiedades_venta).
-- ----------------------------------------------------------------------------

-- `roles.ambito_restringido` ya existe y controla el alcance sobre la cartera
-- (propiedades/proyectos). El alcance sobre el catálogo de venta es un
-- concepto aparte (un rol podría ver toda la cartera pero solo un pedazo del
-- catálogo, o viceversa), así que necesita su propia bandera.
alter table roles
  add column if not exists ambito_restringido_venta boolean not null default true;

comment on column roles.ambito_restringido_venta is 'Si es true, este rol solo ve las propiedades/proyectos de venta listados en roles_propiedades_venta / roles_proyectos_venta. Default true a propósito: un rol nuevo de asesor no debe ver todo el catálogo hasta que un admin se lo asigne explícitamente.';

create table if not exists roles_proyectos_venta (
  rol_id bigint not null references roles(id) on delete cascade, -- [VERIFICAR TIPO]
  proyecto_venta_id bigint not null references proyectos_venta(id) on delete cascade, -- [VERIFICAR TIPO]
  primary key (rol_id, proyecto_venta_id)
);

create table if not exists roles_propiedades_venta (
  rol_id bigint not null references roles(id) on delete cascade, -- [VERIFICAR TIPO]
  propiedad_venta_id bigint not null references propiedades_venta(id) on delete cascade, -- [VERIFICAR TIPO]
  primary key (rol_id, propiedad_venta_id)
);

alter table roles_proyectos_venta enable row level security;
alter table roles_propiedades_venta enable row level security;

-- Solo administradores gestionan el alcance (se edita desde SelectorAlcance en la app).
create policy "admins_gestionan_roles_proyectos_venta"
  on roles_proyectos_venta for all
  to authenticated
  using (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  )
  with check (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  );

create policy "admins_gestionan_roles_propiedades_venta"
  on roles_propiedades_venta for all
  to authenticated
  using (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  )
  with check (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  );

-- Asesores y equipo autenticado pueden leer su propio alcance (para que la
-- pantalla del asesor sepa qué mostrar); no pueden modificarlo.
create policy "equipo_lee_roles_proyectos_venta"
  on roles_proyectos_venta for select
  to authenticated
  using (true);

create policy "equipo_lee_roles_propiedades_venta"
  on roles_propiedades_venta for select
  to authenticated
  using (true);

-- ----------------------------------------------------------------------------
-- 4. Control de intentos fallidos de código (equipo/asesores).
-- ----------------------------------------------------------------------------

create table if not exists intentos_login (
  id bigserial primary key,
  codigo_intentado text,
  ip text,
  exito boolean not null default false,
  creado_en timestamptz not null default now()
);

create index if not exists intentos_login_idx on intentos_login (ip, creado_en desc);

comment on table intentos_login is 'Registro de intentos de login por código (equipo/asesores), usado por la Edge Function validar-codigo-acceso para bloquear tras 5 intentos fallidos en 15 minutos desde la misma IP.';

alter table intentos_login enable row level security;
-- Sin policies: solo la Edge Function (con la llave de servicio, que ignora RLS)
-- lee y escribe aquí. Nadie más, ni siquiera el equipo autenticado.

-- ----------------------------------------------------------------------------
-- 5. Rol de asesor externo (permisos base; el alcance de cada asesor real se
--    define clonando este rol con SelectorAlcance en la pantalla Equipo → Roles,
--    igual que ya se hace hoy con los roles de staff).
-- ----------------------------------------------------------------------------

insert into roles (nombre, es_administrador, permisos, ambito_restringido)
values (
  'Asesor externo',
  false,
  '{
    "ver_propiedades_asignadas": true,
    "ver_precio_lista": true,
    "ver_precio_minimo": true,
    "cotizar": true,
    "enviar_cotizacion": true
  }'::jsonb,
  true
)
on conflict do nothing;

-- Rol de asesor interno: arranca igual al externo; agrega permisos según se
-- decida (usa la pantalla Equipo → Roles para eso, no hace falta migración).
insert into roles (nombre, es_administrador, permisos, ambito_restringido)
values (
  'Asesor interno',
  false,
  '{
    "ver_propiedades_asignadas": true,
    "ver_precio_lista": true,
    "ver_precio_minimo": true,
    "cotizar": true,
    "enviar_cotizacion": true
  }'::jsonb,
  true
)
on conflict do nothing;

-- ----------------------------------------------------------------------------
-- 6. RLS de propiedades_venta_condiciones: equipo interno (admin o con
--    ver_precio_lista/ver_precio_minimo) y asesores dentro de su alcance.
--    Nunca el rol anon/público.
-- ----------------------------------------------------------------------------

create policy "equipo_y_asesores_leen_condiciones_en_su_alcance"
  on propiedades_venta_condiciones for select
  to authenticated
  using (
    exists (
      select 1
      from usuarios u
      join roles r on r.id = u.rol_id
      where u.id = auth.uid()
        and u.activo
        and (
          r.es_administrador
          or (
            (r.permisos ->> 'ver_precio_lista')::boolean is true
            or (r.permisos ->> 'ver_precio_minimo')::boolean is true
          )
        )
        and (
          r.es_administrador
          or not r.ambito_restringido_venta
          or exists (
            select 1 from roles_propiedades_venta rpv
            where rpv.rol_id = r.id and rpv.propiedad_venta_id = propiedades_venta_condiciones.propiedad_venta_id
          )
          or exists (
            select 1 from roles_proyectos_venta rpjv
            join propiedades_venta pv on pv.proyecto_venta_id = rpjv.proyecto_venta_id
            where rpjv.rol_id = r.id and pv.id = propiedades_venta_condiciones.propiedad_venta_id
          )
        )
    )
  );

create policy "admins_escriben_condiciones"
  on propiedades_venta_condiciones for all
  to authenticated
  using (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  )
  with check (
    exists (
      select 1 from usuarios u join roles r on r.id = u.rol_id
      where u.id = auth.uid() and u.activo and r.es_administrador
    )
  );

-- ----------------------------------------------------------------------------
-- 7. RLS de propiedades_venta / fotos_propiedad_venta: agrega lectura para
--    asesores dentro de su alcance. LA POLICY PÚBLICA EXISTENTE (catálogo del
--    sitio web) NO se toca — esto solo suma una policy más para el caso de
--    un asesor autenticado (que hoy, si no está en su alcance restringido,
--    de todas formas ya vería el catálogo completo vía la policy pública;
--    esta policy es principalmente para cuando en el futuro se quiera cerrar
--    esa policy pública o mostrar solo "asignadas" server-side).
-- ----------------------------------------------------------------------------

create policy "asesores_leen_propiedades_venta_en_su_alcance"
  on propiedades_venta for select
  to authenticated
  using (
    exists (
      select 1
      from usuarios u
      join roles r on r.id = u.rol_id
      where u.id = auth.uid()
        and u.activo
        and (r.permisos ->> 'ver_propiedades_asignadas')::boolean is true
        and (
          r.es_administrador
          or not r.ambito_restringido_venta
          or exists (
            select 1 from roles_propiedades_venta rpv
            where rpv.rol_id = r.id and rpv.propiedad_venta_id = propiedades_venta.id
          )
          or exists (
            select 1 from roles_proyectos_venta rpjv
            where rpjv.rol_id = r.id and rpjv.proyecto_venta_id = propiedades_venta.proyecto_venta_id
          )
        )
    )
  );

-- NOTA IMPORTANTE: revisa en Supabase Studio que NINGUNA policy existente en
-- `cuotas`, `comprobantes` o `clientes` sea "true para todo authenticated" —
-- deben seguir excluyendo a los nuevos usuarios.tipo = 'asesor_interno' /
-- 'asesor_externo'. Con RLS activado y sin policy que los cubra, por defecto
-- NO tienen acceso — pero si alguna policy vieja dice simplemente
-- "to authenticated using (true)", un asesor SÍ entraría por ahí. Este script
-- no puede detectar eso sin leer tus policies reales.

commit;
